# Conditional Output: Stack AWS Execution Role Arn
# This value is null if the create_iam_role bool is false
output "role_arn" {
  description = "ARN of the IAM role created for the Spacelift stack AWS integration. Null when create_iam_role is false."
  value       = var.create_iam_role ? aws_iam_role.this[0].arn : null
}

# The id of the created stack
output "id" {
  description = "The ID of the created Spacelift stack."
  value       = spacelift_stack.this.id
}

# The AWS IAM assume-role policy statement generated by Spacelift
output "aws_assume_role_policy_statement" {
  description = "AWS IAM assume-role policy statement that sets up the trust relationship with Spacelift. Use this in your IAM role's trust policy when not using create_iam_role."
  value       = var.setup_aws_integration ? data.spacelift_aws_integration_attachment_external_id.this[0].assume_role_policy_statement : null
}
