# ---------------------------------------------------------------------------
# Required
# ---------------------------------------------------------------------------

variable "role_name_prefix" {
  type        = string
  description = "Prefix used to name both IAM roles. Creates `<prefix>-read` and `<prefix>-write` roles."
}

variable "read_assume_role_policy_statement" {
  type        = string
  description = "JSON trust-policy statement generated by `spacelift_aws_integration_attachment_external_id` for the read integration. Passed directly from the root module output `read_assume_role_policy_statement`."
}

variable "write_assume_role_policy_statement" {
  type        = string
  description = "JSON trust-policy statement generated by `spacelift_aws_integration_attachment_external_id` for the write integration. Passed directly from the root module output `write_assume_role_policy_statement`."
}

# ---------------------------------------------------------------------------
# Optional
# ---------------------------------------------------------------------------

variable "aws_region" {
  type        = string
  description = "AWS region for the AWS provider. Has no effect on which region resources are deployed in—only which regional STS endpoint is used for provider authentication."
  default     = "us-east-1"
}

variable "create_read_role" {
  type        = bool
  description = "Whether to create the read (plan) IAM role."
  default     = true
}

variable "create_write_role" {
  type        = bool
  description = "Whether to create the write (apply) IAM role."
  default     = true
}

variable "read_role_policy_arns" {
  type        = list(string)
  description = "List of IAM managed policy ARNs to attach to the read (plan) IAM role."
  default     = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
}

variable "write_role_policy_arns" {
  type        = list(string)
  description = "List of IAM managed policy ARNs to attach to the write (apply) IAM role."
  default     = ["arn:aws:iam::aws:policy/PowerUserAccess"]
}

variable "read_additional_external_ids" {
  type        = list(string)
  description = "Additional external IDs to include alongside the Spacelift-generated ID in the read role's STS trust policy condition. Useful when multiple Spacelift stacks or external principals also need to assume this role."
  default     = []
}

variable "write_additional_external_ids" {
  type        = list(string)
  description = "Additional external IDs to include alongside the Spacelift-generated ID in the write role's STS trust policy condition. Useful when multiple Spacelift stacks or external principals also need to assume this role."
  default     = []
}

variable "tags" {
  type        = map(string)
  description = "Additional tags to apply to the IAM roles."
  default     = {}
}
